apiVersion: v1
kind: Service
metadata:
  name: supplier-service
  labels:
    app: supplier-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: ctse-app
  sessionAffinity: None
