name: Docker Build Deploy
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: run shell script
      run: echo commit hash is ${{ github.sha }}
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} 
  # - name: Build the Docker image
  #   run: docker build . --file Dockerfile --tag my-image-name:${{ github.sha}}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/supplier:${{ github.sha }}
        
        
        
        # This is a basic workflow to help you get started with Actions

# name: Docker Build Deploy

# on:
#   push:
#     branches:
#        [main]
#     tags:
#       - 'v*'
#   pull_request:
#     branches:
#       - 'main'

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       -
#         name: Checkout 
#         uses: actions/checkout@v2
#       -
#         name: Login to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_HUB_USERNAME }}
#           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#       -
#         name: Build and push
#         uses: docker/build-push-action@v2
#         with:
#           context: ./
#           file: ./Dockerfile
#           builder: ${{ steps.buildx.outputs.name }}
#           push: true
#           tags: ${{ secrets.DOCKER_HUB_USERNAME }}/supplier:latest
# #           cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/supplier:buildcache
# #           cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/supplier:buildcache,mode=max







